from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path
from types import SimpleNamespace
from typing import Any

from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi

from .api import build_api_router
from .mcp_server import build_mcp

API_VERSION = "0.4.1"
MCP_PROTOCOL_BASELINE = "2025-06-18"

_HTTP_METHODS = frozenset({"get", "post", "put", "patch", "delete", "options", "head"})
_DOMAIN_RESPONSES: dict[str, dict[str, str]] = {
    "agentsGet": {"404": "Agent not found."},
    "agentsRegister": {
        "409": "A different definition is already registered.",
        "422": "The definition or Compose project is invalid.",
    },
    "agentConfigurationUpdate": {"404": "Agent not found."},
    "jobsSubmit": {
        "404": "Agent or companion stage not found, or the agent is disabled.",
        "409": "Conversation or companion stage state conflicts with this submission.",
        "413": "A companion or conversation companion limit would be exceeded.",
        "422": "A companion binding is invalid.",
        "507": "Companion staging capacity is exhausted.",
    },
    "companionStagesUpload": {
        "409": "The companion stage conflicts with current state.",
        "413": "The uploaded or expanded companion exceeds a configured limit.",
        "422": "The filename, kind, digest, or archive is invalid.",
        "507": "Companion staging capacity is exhausted.",
    },
    "companionStagesGitImport": {
        "409": "The companion stage conflicts with current state.",
        "413": "The imported repository exceeds a configured limit.",
        "422": "The repository URL, ref, or imported tree is invalid or disallowed.",
        "507": "Companion staging capacity is exhausted.",
    },
    "companionStagesGet": {"404": "Companion stage not found."},
    "conversationCompanionsList": {"404": "Conversation not found."},
    "jobsGet": {"404": "Job not found."},
    "jobsCancel": {"404": "Job not found."},
    "conversationArchive": {
        "404": "Conversation not found.",
        "409": "Conversation has active jobs or an invalid state.",
    },
    "conversationDelete": {
        "404": "Conversation not found.",
        "409": "Conversation has active jobs.",
    },
    "artifactsGet": {"404": "Artifact not found."},
    "artifactContentGet": {
        "400": "Malformed byte range.",
        "404": "Artifact not found.",
        "410": "Artifact storage is unavailable or violates policy.",
        "416": "Requested byte range is not satisfiable.",
    },
}


def configure_openapi(app: FastAPI) -> None:
    """Install the supported HTTP client contract on a FastAPI application."""

    def openapi() -> dict[str, Any]:
        if app.openapi_schema is not None:
            return app.openapi_schema
        schema = get_openapi(
            title=app.title,
            version=app.version,
            description=(
                "Versioned RemoteAgent control API. The MCP protocol at `/mcp`, "
                "dashboard projection routes, and Prometheus metrics are documented "
                "separately and are not part of this OpenAPI contract."
            ),
            routes=app.routes,
            openapi_version=app.openapi_version,
        )
        schema["servers"] = [
            {
                "url": "{scheme}://{host}:{port}",
                "description": "RemoteAgent router",
                "variables": {
                    "scheme": {"default": "http", "enum": ["http", "https"]},
                    "host": {"default": "localhost"},
                    "port": {"default": "8080"},
                },
            }
        ]
        schema["tags"] = [
            {"name": "Agents", "description": "Agent discovery and immutable definitions."},
            {"name": "Jobs", "description": "Asynchronous prompt jobs and polling."},
            {"name": "Conversations", "description": "Conversation lifecycle operations."},
            {
                "name": "Companions",
                "description": "Persistent conversation-owned input files and repositories.",
            },
            {"name": "Artifacts", "description": "Immutable agent-produced artifacts."},
        ]
        components = schema.setdefault("components", {})
        components.setdefault("securitySchemes", {})["bearerAuth"] = {
            "type": "http",
            "scheme": "bearer",
            "description": "Router bearer token generated by `remotectl init`.",
        }
        components.setdefault("schemas", {})["ErrorResponse"] = {
            "type": "object",
            "required": ["detail"],
            "properties": {"detail": {"type": "string"}},
            "additionalProperties": False,
        }
        schema["security"] = [{"bearerAuth": []}]

        for path_item in schema.get("paths", {}).values():
            for method, operation in path_item.items():
                if method not in _HTTP_METHODS or not isinstance(operation, dict):
                    continue
                responses = operation.setdefault("responses", {})
                responses.setdefault(
                    "401",
                    {
                        "description": "Missing or invalid bearer token.",
                        "headers": {
                            "WWW-Authenticate": {
                                "schema": {"type": "string"},
                                "description": "Always `Bearer`.",
                            }
                        },
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/ErrorResponse"}
                            }
                        },
                    },
                )
                operation_id = operation.get("operationId")
                for status, description in _DOMAIN_RESPONSES.get(operation_id, {}).items():
                    responses.setdefault(
                        status,
                        {
                            "description": description,
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/ErrorResponse"}
                                }
                            },
                        },
                    )

        artifact_content = schema["paths"]["/api/v1/artifacts/{artifact_id}/content"]["get"]
        artifact_content.setdefault("parameters", []).append(
            {
                "name": "Range",
                "in": "header",
                "required": False,
                "description": "Optional RFC 7233 byte range, for example `bytes=0-1023`.",
                "schema": {"type": "string"},
            }
        )
        binary_response = {
            "description": "Artifact bytes.",
            "headers": {
                "ETag": {"schema": {"type": "string"}},
                "Accept-Ranges": {"schema": {"type": "string", "const": "bytes"}},
                "Cache-Control": {"schema": {"type": "string", "const": "private, immutable"}},
                "Content-Disposition": {"schema": {"type": "string"}},
            },
            "content": {
                "application/octet-stream": {"schema": {"type": "string", "format": "binary"}}
            },
        }
        artifact_content["responses"]["200"] = binary_response
        artifact_content["responses"]["206"] = {
            **binary_response,
            "description": "Requested artifact byte range.",
            "headers": {
                **binary_response["headers"],
                "Content-Range": {"schema": {"type": "string"}},
            },
        }
        companion_upload = schema["paths"]["/api/v1/companion-stages/uploads"]["post"]
        companion_upload["requestBody"] = {
            "required": True,
            "description": "Raw bytes for one ordinary file or supported archive.",
            "content": {
                "application/octet-stream": {
                    "schema": {"type": "string", "format": "binary"}
                }
            },
        }
        app.openapi_schema = schema
        return schema

    app.openapi = openapi  # type: ignore[method-assign]


def build_openapi_contract() -> dict[str, Any]:
    app = FastAPI(title="RemoteAgent Router", version=API_VERSION)
    app.include_router(build_api_router())
    configure_openapi(app)
    return app.openapi()


async def build_mcp_contracts() -> tuple[dict[str, Any], dict[str, Any]]:
    settings = SimpleNamespace(
        mcp_mount_path="/mcp",
        mcp_dns_rebinding_protection=True,
        mcp_allowed_hosts=["127.0.0.1:*", "localhost:*", "[::1]:*"],
        mcp_allowed_origins=[
            "http://127.0.0.1:*",
            "http://localhost:*",
            "http://[::1]:*",
        ],
    )
    server = build_mcp(
        SimpleNamespace(
            settings=settings,
            agent_service=None,
            job_service=None,
            artifact_service=None,
            companion_service=None,
        )
    )
    tools = [
        tool.model_dump(mode="json", by_alias=True, exclude_none=True)
        for tool in await server.list_tools()
    ]
    templates = [
        template.model_dump(mode="json", by_alias=True, exclude_none=True)
        for template in await server.list_resource_templates()
    ]
    return {"tools": tools}, {"resourceTemplates": templates}


async def contract_documents() -> dict[str, dict[str, Any]]:
    tools, templates = await build_mcp_contracts()
    return {
        "openapi.json": build_openapi_contract(),
        "mcp-tools-list.json": tools,
        "mcp-resource-templates-list.json": templates,
    }


def _encoded(value: dict[str, Any]) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


async def _run(output_dir: Path, *, check: bool) -> int:
    documents = await contract_documents()
    stale: list[Path] = []
    for name, value in documents.items():
        path = output_dir / name
        expected = _encoded(value)
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                stale.append(path)
            continue
        output_dir.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
        print(f"wrote {path}")
    if stale:
        for path in stale:
            print(f"stale API contract: {path}")
        return 1
    if check:
        print("API contracts are current")
    return 0


def main() -> None:
    repository_root = Path(__file__).resolve().parents[3]
    parser = argparse.ArgumentParser(description="Export checked-in API contracts")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=repository_root / "docs" / "api",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when checked-in contracts differ from current code",
    )
    arguments = parser.parse_args()
    raise SystemExit(asyncio.run(_run(arguments.output_dir.resolve(), check=arguments.check)))


if __name__ == "__main__":
    main()
